name: Update Version

on:
  push:
    branches:
      - main
      - develop

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Update version
        run: |
          # Increment the version
          npm version patch --no-git-tag-version

          # Commit and push the changes
          git config user.name "user-name"
          git config user.email "user-email@mail.com"
          git add package.json
          git commit -m "update package.json version"
          git push origin $(echo $GITHUB_REF | cut -d'/' -f 3)
